#!/bin/bash
if [[ $EUID -ne 0 ]]; then
  echo "You should run this script with 'sudo' or logged in as root!"
  exit 1
fi

echo "Running 'apt update' to look for missing keys"
missing_keys=$(apt update 2>&1 1>/dev/null|grep 'NO_PUBKEY'|grep -oE '[^ ]+$')
missing_keys=$( echo $missing_keys | xargs -n1 | sort -u | xargs )
key_count=$(echo $missing_keys|wc -w)
echo "Found ${key_count} missing key(s)"
for key in $missing_keys; do
  echo "Adding missing GPG key: ${key}"
  gpg --keyserver pgp.mit.edu --recv-keys ${key} >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    gpg -a --export ${key} | apt-key add -
  else
    echo "Error getting GPG key ${key}"
  fi
done
if [[ $key_count -gt 0 ]]; then 
  echo "Done!  You should run 'apt update' again."
else
  echo "No missing keys detected."
fi
